// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4sgUaGgEmfw5VHSviUufX2Ilxpts0xg',
    appId: '1:716118676610:web:e7d3647a50c2506977909b',
    messagingSenderId: '716118676610',
    projectId: 'propadvisor-bc710',
    authDomain: 'propadvisor-bc710.firebaseapp.com',
    storageBucket: 'propadvisor-bc710.firebasestorage.app',
    measurementId: 'G-MKJT6J70C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0plK0aHARvW1oz4WB7EpDVj1eis2K2g',
    appId: '1:716118676610:android:7e056895b8df703977909b',
    messagingSenderId: '716118676610',
    projectId: 'propadvisor-bc710',
    storageBucket: 'propadvisor-bc710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZD8o-iRAx0lDXT417k1c3UFSlo-t7nE',
    appId: '1:716118676610:ios:243f92f7c4aa180777909b',
    messagingSenderId: '716118676610',
    projectId: 'propadvisor-bc710',
    storageBucket: 'propadvisor-bc710.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZD8o-iRAx0lDXT417k1c3UFSlo-t7nE',
    appId: '1:716118676610:ios:243f92f7c4aa180777909b',
    messagingSenderId: '716118676610',
    projectId: 'propadvisor-bc710',
    storageBucket: 'propadvisor-bc710.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-4sgUaGgEmfw5VHSviUufX2Ilxpts0xg',
    appId: '1:716118676610:web:3bc81c454a1feb3877909b',
    messagingSenderId: '716118676610',
    projectId: 'propadvisor-bc710',
    authDomain: 'propadvisor-bc710.firebaseapp.com',
    storageBucket: 'propadvisor-bc710.firebasestorage.app',
    measurementId: 'G-NQT5DSJWT7',
  );
}
